name: Auto-Book Lidl Data

on:
  schedule:
    # Запускать каждые 30 минут. Синтаксис Cron.
    - cron: '*/30 * * * *'
  workflow_dispatch: # Позволяет запускать скрипт кнопкой вручную

jobs:
  book_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        env:
          LIDL_PHONE: ${{ secrets.LIDL_PHONE }}
          LIDL_PASSWORD: ${{ secrets.LIDL_PASSWORD }}
        run: python lidl_cloud.py
